args:
  %{ for arg in args ~}
- "${arg}"
  %{ endfor ~}

configuration:
  values:
  %{ for key, value in config_values ~}
    ${key}: "${value}"
  %{ endfor ~}
  
  %{ if length(init_scripts) > 0 ~}
initScripts:
  %{ for script in init_scripts ~}
  - "${script}"
  %{ endfor ~}
  %{ endif ~}
  
  %{ if aws_iam_role_arn != "" ~}
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${aws_iam_role_arn}"
  %{ endif ~}

image:
  tag: "${image_tag}"