hostedZoneName: "${hosted_zone_name}"
namespacecontroller:
  name: "${namespace}"

nullPlatform:
  accountSlug: "${account_slug}"

gcp:
  enabled: ${gcp_enabled}
  serviceAccountKey: |-
    ${gcp_service_account_key}

azure:
  enabled: ${azure_enabled}
  subscriptionId: "${azure_subscription_id}"
  resourceGroupName: "${azure_resource_group_name}"
  clientId: "${azure_client_id}"
  secretKey: "${azure_secret_key}"   # e.g. "client-secret"
  clientSecret: "${azure_client_secret}"
  tenantId: "${azure_tenant_id}"
  hostedZoneName: "${azure_hosted_zone_name}"

cloudflare:
  enabled: ${cloudflare_enabled}
  secretName: "${cloudflare_secret_name}"
  apiToken: "${cloudflare_token}"
